# Generated by Django 3.2.16 on 2025-03-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_level', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=20, unique=True)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('threshold', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
            ],
        ),
    ]
